### ISSUE TITLE
wpimage

### ISSUE THREAD

**Issue by AppleInternal** [Empyreal96/Andromeda_16266#1]
i tried making ffu with wpimage on 12 PCs of my friends with various builds of Windows on PC Host, and Windows Driver Kit builds that wpimage shipped with 

![image (1)](https://github.com/user-attachments/assets/710ef12b-6036-4032-a601-aa91c3ffe28e)

wpimage is very buggy, please upload normal flashable FFU with production PLAT

**Comment by Empyreal96** [comment]
Someone else had this issue, the wpimage you use is too new

Try these
https://github.com/Empyreal96/Updating-WP-FFUs-Guide/blob/main/W10M_Tools.7z

**Comment by Empyreal96** [comment]
This is now obsolete as modifications by the user are no longer required. Closing (:
